name: ecomm
description: "Flutter eCommerce app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  flutter_layout_grid: ^2.0.1
  go_router: ^14.6.2
  flutter_riverpod: ^2.1.1
  uuid: ^4.5.1
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.5.2
  # chapasdk: ^0.0.7+1

  # flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
